name: Update Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'  # Каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Take screenshot
        uses: peter-evans/screenshot-website@v1
        with:
          url: "https://skyline.github.com/mogilevtsevdmitry/2024"  # Официальный URL
          output: "skyline.png"
          delay: 30000  # 30 секунд для рендеринга WebGL
          viewportWidth: 1200
          viewportHeight: 800
          args: "--no-sandbox --disable-setuid-sandbox --user-agent='Mozilla/5.0'"

      - name: Save screenshot
        run: |
          mkdir -p assets
          mv skyline.png assets/skyline.png

      - name: Update README
        run: |
          sed -i 's|!\[GitHub Skyline\](.*)|![GitHub Skyline](assets/skyline.png)|' README.md

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline screenshot"
