name: GitHub-Profile-3D-Contrib
on:
  schedule:
    # Запуск ежедневно в 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:       # ручной запуск из вкладки Actions
permissions:
  contents: write          # разрешение на push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
