name: 3D Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgbm-dev libxshmfence-dev libglu1-mesa-dev
          npm install puppeteer@19.11.1  # Версия с лучшей WebGL поддержкой

      - name: Create assets directory
        run: mkdir -p assets

      - name: Take screenshot with WebGL
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          (async () => {
            const browser = await puppeteer.launch({
              headless: 'new',
              args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--use-gl=egl',  # Критически важно для WebGL
                '--enable-webgl',
                '--enable-accelerated-2d-canvas',
                '--enable-gpu-rasterization',
                '--ignore-gpu-blocklist',
                '--window-size=1400,800'
              ],
              env: {
                DISPLAY: ':99'  # Необходимо для GPU-рендеринга
              }
            });
            
            try {
              const page = await browser.newPage();
              await page.setViewport({ width: 1400, height: 800 });
              
              console.log('Loading Skyline...');
              await page.goto('https://git-skyline.huakun.tech/contribution/github/${{ github.repository_owner }}?enableZoom=false&autoRotate=false', {
                waitUntil: 'networkidle2',
                timeout: 120000
              });
              
              console.log('Waiting for WebGL initialization...');
              await page.waitForFunction(() => {
                const canvas = document.querySelector('canvas');
                return canvas && canvas.getContext('webgl');
              }, { timeout: 120000 });
              
              console.log('Additional rendering time...');
              await new Promise(resolve => setTimeout(resolve, 30000));
              
              console.log('Capturing screenshot...');
              await page.screenshot({
                path: 'assets/skyline.png',
                type: 'png',
                clip: { x: 0, y: 0, width: 1400, height: 800 }
              });
              
            } finally {
              await browser.close();
            }
          })();
          "

      - name: Verify screenshot
        run: |
          ls -la assets/
          [ -s assets/skyline.png ] || (echo "Screenshot failed!" && exit 1)
          file assets/skyline.png

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update 3D Skyline screenshot"
          file_pattern: "assets/skyline.png"
