name: Update Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Playwright
        run: |
          npm init playwright@latest --yes
          npx playwright install-deps

      - name: Take screenshot
        run: |
          mkdir -p assets
          node -e "
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch({
              headless: true,
              timeout: 300000
            });
            
            try {
              const page = await browser.newPage();
              await page.setViewportSize({ width: 1400, height: 1000 });
              
              console.log('Navigating to Skyline...');
              await page.goto('https://skyline.github.com/${{ github.repository_owner }}/2024', {
                waitUntil: 'networkidle',
                timeout: 300000
              });
              
              console.log('Waiting for visualization (up to 3 minutes)...');
              await page.waitForSelector('canvas', { state: 'attached', timeout: 180000 });
              await page.waitForFunction(() => {
                const canvas = document.querySelector('canvas');
                return canvas && canvas.width > 100 && canvas.height > 100;
              }, { timeout: 180000 });
              
              console.log('Additional waiting for WebGL render...');
              await new Promise(resolve => setTimeout(resolve, 60000));
              
              console.log('Taking screenshot...');
              await page.screenshot({
                path: 'assets/skyline.png',
                type: 'png',
                fullPage: false,
                animations: 'disabled',
                timeout: 60000
              });
              
              console.log('Screenshot saved successfully');
            } finally {
              await browser.close();
            }
          })();
          "

      - name: Verify screenshot
        run: |
          ls -la assets/
          [ -s assets/skyline.png ] || (echo "Screenshot is empty!" && exit 1)
          file assets/skyline.png

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline screenshot"
          file_pattern: "assets/skyline.png"
