name: Update Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Увеличиваем таймаут

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install puppeteer
          sudo apt-get install -y libgbm-dev  # Для поддержки Chrome в Linux

      - name: Take screenshot
        uses: docker://ghcr.io/puppeteer/puppeteer:latest
        with:
          entrypoint: node
          args: |
            -e "
            const puppeteer = require('puppeteer');
            (async () => {
              const browser = await puppeteer.launch();
              const page = await browser.newPage();
              await page.goto('https://skyline.github.com/${{ github.repository_owner }}/2024', {waitUntil: 'networkidle2'});
              await new Promise(resolve => setTimeout(resolve, 30000));
              await page.screenshot({path: '/github/workspace/assets/skyline.png'});
              await browser.close();
            })();
            "

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline screenshot"
          file_pattern: "assets/skyline.png"
