name: Update Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          mkdir -p assets
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Take screenshot using Python
        run: |
          python3 -c "
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          import time

          options = Options()
          options.add_argument('--no-sandbox')
          options.add_argument('--disable-dev-shm-usage')
          options.add_argument('--headless')
          options.binary_location = '/usr/bin/chromium-browser'

          driver = webdriver.Chrome(options=options)
          driver.set_window_size(1200, 800)
          driver.get('https://skyline.github.com/${{ github.repository_owner }}/2024')
          
          # Ждем полной загрузки
          time.sleep(30)
          
          # Сохраняем прямо в нужную папку
          driver.save_screenshot('assets/skyline.png')
          driver.quit()
          "

      - name: Verify screenshot
        run: |
          file assets/skyline.png
          [ -s assets/skyline.png ] || exit 1

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline screenshot"
          file_pattern: "assets/skyline.png"
