name: Update Skyline Visualization

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - name: Download Skyline SVG
        run: |
          mkdir -p assets
          curl -s "https://skyline.github.com/${{ github.repository_owner }}/2024.svg" -o assets/skyline.svg
          
          # Конвертируем SVG в PNG (опционально)
          if ! command -v inkscape &> /dev/null; then
            sudo apt-get update && sudo apt-get install -y inkscape
          fi
          inkscape --export-type=png -w 1400 -h 800 assets/skyline.svg -o assets/skyline.png

      - name: Verify files
        run: |
          ls -la assets/
          [ -s assets/skyline.svg ] || (echo "SVG file is empty!" && exit 1)
          [ ! -f assets/skyline.png ] || [ -s assets/skyline.png ] || (echo "PNG file is empty!" && exit 1)

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline visualization"
          file_pattern: assets/*
