name: Update Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup Firefox (geckodriver)
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox-esr
          wget https://github.com/mozilla/geckodriver/releases/download/v0.34.0/geckodriver-v0.34.0-linux64.tar.gz
          tar -xvzf geckodriver*
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Take screenshot with direct path control
        run: |
          mkdir -p assets
          python3 -c "
          from selenium import webdriver
          from selenium.webdriver.firefox.options import Options
          import time

          options = Options()
          options.headless = True
          driver = webdriver.Firefox(options=options)
          
          try:
              driver.set_window_size(1200, 800)
              driver.get('https://skyline.github.com/${{ github.repository_owner }}/2024')
              time.sleep(45)  # Максимальное время для WebGL
              
              # Явное сохранение по абсолютному пути
              driver.save_screenshot('$GITHUB_WORKSPACE/assets/skyline.png')
          finally:
              driver.quit()
          "

      - name: Verify file existence
        run: |
          ls -la assets/
          [ -f assets/skyline.png ] || (echo "Файл не создан!" && exit 1)
          file assets/skyline.png

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline screenshot"
          file_pattern: "assets/skyline.png"
