name: Update Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'  # Каждый день в 00:00 UTC
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Критически важно для доступа к репозиторию

      - name: Create assets directory
        run: mkdir -p assets  # Создаем папку заранее

      - name: Take screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: "https://skyline.github.com/mogilevtsevdmitry/2024"
          destination: "screenshot.png"  # Сохраняем в корень временной папки
          width: 1200
          height: 800
          delay: 30000  # 30 секунд для рендеринга WebGL
          args: "--no-sandbox --disable-setuid-sandbox"

      - name: Move screenshot to assets
        run: mv screenshot.png assets/skyline.png  # Переносим в нужную папку

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline screenshot"
          file_pattern: "assets/skyline.png"
