name: Update Skyline Screenshot
on:
  schedule:
    - cron: '0 0 * * *' # Еженедельно
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Take screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://git-skyline.huakun.tech/contribution/github/${{ github.repository_owner }}/embed?enableZoom=false&autoRotate=false
          destination: assets/skyline.png
          width: 800
          height: 600
      - name: Commit screenshot
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/skyline.png
          git commit -m "Update skyline screenshot" || exit 0
          git push
