name: Skyline Screenshot Simplified

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Setup minimal environment
        run: |
          sudo apt-get update || true
          sudo apt-get install -y --no-install-recommends \
            chromium-browser \
            imagemagick

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer@19.11.1 --no-fund --no-audit

      - name: Create assets directory
        run: mkdir -p assets

      - name: Take screenshot (headless)
        run: |
          node <<EOF
          const puppeteer = require('puppeteer');
          
          (async () => {
            const browser = await puppeteer.launch({
              executablePath: '/usr/bin/chromium-browser',
              headless: 'new',
              args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--enable-webgl',
                '--use-angle=gl-egl'
              ]
            });

            try {
              const page = await browser.newPage();
              await page.setViewport({ width: 1400, height: 800 });
              
              console.log('Loading page...');
              await page.goto('https://git-skyline.huakun.tech/contribution/github/${{ github.repository_owner }}', {
                waitUntil: 'domcontentloaded',
                timeout: 45000
              });

              console.log('Basic content check...');
              await page.waitForFunction(
                () => document.body.innerText.includes('GitHub'),
                { timeout: 30000 }
              );

              console.log('Capturing screenshot...');
              await page.screenshot({
                path: 'assets/skyline.png',
                type: 'png',
                fullPage: false
              });

            } catch (error) {
              console.error('Error:', error.message);
              process.exit(1);
            } finally {
              await browser.close();
            }
          })();
          EOF

      - name: Generate fallback if empty
        if: failure()
        run: |
          convert -size 1400x800 xc:#0d1117 \
            -fill white -pointsize 40 -gravity center \
            -annotate +0+0 "GitHub Skyline\nCurrently Unavailable" \
            assets/skyline.png

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline snapshot"
          file_pattern: "assets/skyline.png"
