name: Reliable Skyline Capture

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment (safe mode)
        run: |
          # Ожидаем освобождения блокировки
          while sudo fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
            echo "Waiting for package manager to unlock..."
            sleep 5
          done

          # Устанавливаем только необходимые пакеты
          sudo apt-get update -o Acquire::Retries=3 || true
          sudo apt-get install -y \
            --no-install-recommends \
            libgbm1 \
            libxshmfence1 \
            libglu1-mesa \
            xvfb \
            imagemagick \
            chromium \
            fonts-freefont-ttf

          # Чистка кеша
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*

      - name: Install Node.js dependencies
        run: |
          npm install puppeteer@19.11.1 --no-fund --no-audit

      - name: Create assets directory
        run: mkdir -p assets

      - name: Capture Skyline (simplified)
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1920x1080x24 +extension GLX -nolisten tcp &
          
          node <<EOF
          const puppeteer = require('puppeteer');
          
          (async () => {
            const browser = await puppeteer.launch({
              executablePath: '/usr/bin/chromium',
              headless: 'new',
              args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--window-size=1920,1080'
              ]
            });

            try {
              const page = await browser.newPage();
              await page.goto('https://git-skyline.huakun.tech/contribution/github/${{ github.repository_owner }}?enableZoom=false', {
                waitUntil: 'domcontentloaded',
                timeout: 60000
              });

              // Простая проверка загрузки
              await page.waitForFunction(() => {
                return document.querySelector('body')?.textContent?.includes('GitHub Skyline');
              }, { timeout: 30000 });

              await new Promise(resolve => setTimeout(resolve, 5000));
              await page.screenshot({ path: 'assets/skyline.png' });
              
            } finally {
              await browser.close();
            }
          })();
          EOF

      - name: Verify result
        run: |
          [ -f assets/skyline.png ] || exit 1
          file assets/skyline.png

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline snapshot"
          file_pattern: "assets/skyline.png"
