name: Update Skyline Screenshot

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Setup environment
        run: |
          mkdir -p assets
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Chromium
        run: |
          wget https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F1234567%2Fchrome-linux.zip?alt=media -O chrome.zip
          unzip chrome.zip
          sudo mv chrome-linux /usr/local/bin/

      - name: Take screenshot
        run: |
          # Установка Node.js и зависимостей
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install puppeteer-core

          # Скрипт для скриншота с увеличенными таймаутами
          node -e "
          const puppeteer = require('puppeteer-core');
          (async () => {
            const browser = await puppeteer.launch({
              executablePath: '/usr/local/bin/chrome-linux/chrome',
              headless: true,
              args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-dev-shm-usage',
                '--disable-gpu',
                '--window-size=1200,800'
              ],
              timeout: 180000
            });

            try {
              const page = await browser.newPage();
              await page.setDefaultNavigationTimeout(180000);
              await page.setDefaultTimeout(180000);
              
              console.log('Navigating to Skyline...');
              await page.goto('https://skyline.github.com/${{ github.repository_owner }}/2024', {
                waitUntil: 'networkidle2',
                timeout: 180000
              });

              console.log('Waiting for canvas...');
              await page.waitForSelector('canvas', { timeout: 120000 });
              
              console.log('Waiting additional 30s for WebGL...');
              await new Promise(resolve => setTimeout(resolve, 30000));

              console.log('Taking screenshot...');
              await page.screenshot({
                path: 'assets/skyline.png',
                fullPage: false,
                type: 'png',
                quality: 100
              });

              console.log('Screenshot saved');
            } finally {
              await browser.close();
            }
          })();
          "

      - name: Verify screenshot
        run: |
          ls -la assets/
          [ -f assets/skyline.png ] || exit 1
          file assets/skyline.png

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Skyline screenshot"
          file_pattern: "assets/skyline.png"
